# Generated by Django 4.1.6 on 2023-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email_user', models.CharField(max_length=255)),
                ('password_user', models.CharField(max_length=255)),
                ('record_date_table', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
