# Generated by Django 4.1.6 on 2023-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email_user', models.CharField(max_length=255)),
                ('password_user', models.CharField(max_length=255)),
                ('country_user', models.CharField(max_length=150)),
                ('province_user', models.CharField(max_length=150)),
                ('city_user', models.CharField(max_length=150)),
                ('birth_date_user', models.DateField(max_length=10)),
                ('level_studies_user', models.CharField(max_length=15)),
                ('record_date_table', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
