# Generated by Django 4.1.6 on 2023-02-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Login',
        ),
    ]
