# Generated by Django 4.1.6 on 2023-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userdata_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name_user',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nickname_user',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
